### ISSUE TITLE
Start Simulation option to be added in Info Template

### ISSUE THREAD

**Issue by ashmitan** [BuildmLearn/Toolkit-mobile-templates#10]
We should make Info Template consistent with other templates and this should also have start simulation option.

**Comment by opticod** [comment]
facility of simulation of info template is present in toolkit. we have also changed the simulator and app design. Its present in https://github.com/BuildmLearn/Toolkit-mobile-templates/tree/master/InfoTemplate/source/InfoTemplateAppV3
