### ISSUE TITLE
Flash card should flip on swipe/fling

### ISSUE THREAD

**Issue by ishan1604** [BuildmLearn/Toolkit-mobile-templates#14]
To make the game feel more real in the hands of the user, we need a natural action to flip a card which on handheld device would be a swipe or a fling instead of pressing a button to flip the image.

**Comment by prasang7** [comment]
Fixed this issue. Now user can swipe right/left to check the answer, along with former approach of 'flip' button. https://github.com/BuildmLearn/BuildmLearn-Toolkit-Android/pull/92

**Comment by opticod** [comment]
Added in #32 . Hence closing for now.
