### ISSUE TITLE
Template data file should be XML format wherever possible

### ISSUE THREAD

**Issue by croozeus** [BuildmLearn/Toolkit-mobile-templates#21]
Templates use a data file - generated from the toolkit and used in the application file. Currently, there is no standard format for these file - we should use XML for the data files. 

For this, changes are required in all the mobile templates. Once these changes are done, please open a request in the BuildmLearn repository.

**Comment by KKcorps** [comment]
Hi all
I just wanted to know why is this issue still open.I went through the code and I saw that XML parser is already implemented in all templates.

**Comment by opticod** [comment]
To my best knowledge, at present all the templates work using XML data. So closing for now.
