### ISSUE TITLE
Quiz Template App

### ISSUE THREAD

**Issue by yogeshmadaan100** [BuildmLearn/Toolkit-mobile-templates#23]
The issue is a typical radio button issue. Radio Button in a radio group is not accepting the same selected button.

Bug Detection Procedure:

Install the apk and start the quiz.
Answer the question as any of the question ( I took Option C in my case)
Click Submit and then next.
As the next question arrives try to click on the same option button as in step 3 ( In My case again Option 3 )
Radio button will not be shown selected until some option other than previous one is selected,

**Comment by opticod** [comment]
Already reported in #7
