### ISSUE TITLE
Duplicates are allowed in all Mobile Templates 

### ISSUE THREAD

**Issue by codingblazer** [BuildmLearn/Toolkit-mobile-templates#44]
In all templates, we can add Duplicate videos, Duplicate Flashcards etc. User should not be allowed to make duplicates or should be informed once that this already exists (for all templates).
@croozeus @opticod Your views on this.

**Comment by opticod** [comment]
Ok, but it should be headed to toolkit repo, isn't ?

**Comment by codingblazer** [comment]
@opticod yeah sure
