### ISSUE TITLE
how to start contributing?

### ISSUE THREAD

**Issue by DravitLochan** [BuildmLearn/Toolkit-mobile-templates#46]
I want to pr some changes which will reduce build time. so please guide me which branch to use and if any syntax of pr has to be followed. :)

**Comment by tejavojjala** [comment]
@DravitLochan you can submit your changes to the master branch. Your pr must pass all checks by travis and codacy. Also if your pr has multiple commits you need to squash them(i.e single commit per pull request)

**Comment by opticod** [comment]
@DravitLochan @tejavojjala Follow new updated Contribution-policy for each repo. You can find it in contribution-policy section of README (https://github.com/BuildmLearn/Toolkit-mobile-templates#contribution-policy)
