### ISSUE TITLE
 Quiz Template on device - radio buttons don't get selected easily

### ISSUE THREAD

**Issue by croozeus** [BuildmLearn/Toolkit-mobile-templates#7]
Radio buttons do not get selected easily until you press and hold it hard on device.

Reported by Ashmita

**Comment by yogeshmadaan100** [comment]
Bug Fixed in Pull Request 24 @croozeus

**Comment by KKcorps** [comment]
It's working fine on my device.

**Comment by opticod** [comment]
Fixed in latest build
